export const mockUsers = [
    {
        email: 'user0@mail.ru',
        role: 'user',
        password: 'user1234',
        name: 'Иван Петров',
        status: 'Люблю спорт!',
        avatar: 'http://localhost:8000/avatar1.webp',
    },
    {
        email: 'trainer@mail.ru',
        role: 'trainer',
        password: 'trainer1234',
        name: 'Артем Иванов',
        status: 'Доведем вас до результата',
        avatar: 'http://localhost:8000/avatar2.webp',
    },
    {
        email: 'admin@mail.ru',
        role: 'admin',
        password: 'admin1234',
        name: 'Виктор Торбосов',
        status: 'Решу ваш вопрос',
        avatar: 'http://localhost:8000/avatar3.webp',
    },
    {
        email: 'user1@mail.ru',
        role: 'user',
        password: 'user1234',
        name: 'Алексей Соколов',
        status: 'Эксперт в кулинарии',
        avatar: 'http://localhost:8000/avatar5.webp',
    },
    {
        email: 'user2@mail.ru',
        role: 'user',
        password: 'user1234',
        name: 'Марина Иванова',
        status: 'Любитель чтения',
        avatar: 'http://localhost:8000/avatar4.webp',
    },
    {
        email: 'user3@mail.ru',
        role: 'user',
        password: 'user1234',
        name: 'Сергей Петров',
        status: 'Фанат кино',
        avatar: 'http://localhost:8000/avatar6.webp',
    },
    {
        email: 'user4@mail.ru',
        role: 'user',
        password: 'user1234',
        name: 'Ольга Смирнова',
        status: 'Активный путешественник',
        avatar: 'http://localhost:8000/avatar8.webp',
    },
    {
        email: 'user5@mail.ru',
        role: 'user',
        password: 'user1234',
        name: 'Дмитрий Иванов',
        status: 'Художник',
        avatar: 'http://localhost:8000/avatar7.webp',
    },
    {
        email: 'user6@mail.ru',
        role: 'user',
        password: 'user1234',
        name: 'Екатерина Орлова',
        status: 'Любитель фитнеса',
        avatar: 'http://localhost:8000/avatar9.webp',
    },
    {
        email: 'user7@mail.ru',
        role: 'user',
        password: 'user1234',
        name: 'Иван Кузнецов',
        status: 'Музыкант',
        avatar: null,
    },
    {
        email: 'user8@mail.ru',
        role: 'user',
        password: 'user1234',
        name: 'Анна Попова',
        status: 'Фотограф',
        avatar: 'http://localhost:8000/avatar10.webp',
    },
    {
        email: 'user9@mail.ru',
        role: 'user',
        password: 'user1234',
        name: 'Владимир Новиков',
        status: 'Программист',
        avatar: 'http://localhost:8000/avatar11.jpg',
    },
    {
        email: 'user10@mail.ru',
        role: 'user',
        password: 'user1234',
        name: 'Наталья Павлова',
        status: 'Любитель животных',
        avatar: 'http://localhost:8000/avatar11.webp',
    },
];

export const mockWorkouts = [
    {
        trainerId: 2,
        title: 'Утренняя зарядка',
        description: 'Зарядка для улучшения общего самочувствия',
        sportType: 'Фитнес',
        status: 'completed',
        maxPlaces: 10,
        dateStart: new Date('2024-05-30T16:00:00'),
        durationMinutes: 60,
    },
    {
        trainerId: 2,
        title: 'Урок йоги для начинающих',
        description: 'Занятие для освоения базовых асан и элементов йоги',
        sportType: 'Йога',
        status: 'canceled',
        maxPlaces: 10,
        dateStart: new Date('2024-05-30T18:00:00'),
        durationMinutes: 60,
    },
    {
        trainerId: 2,
        title: 'Функциональный тренинг для сжигания жира',
        description: 'Интенсивная тренировка для ускорения обмена веществ и сжигания жира',
        sportType: 'Фитнес',
        status: 'completed',
        maxPlaces: 10,
        dateStart: new Date('2024-06-06T14:00:00'),
        durationMinutes: 60,
    },
    {
        trainerId: 2,
        title: 'Кардио тренировка для укрепления сердца',
        description: 'Эта тренировка помогает улучшить работу сердечно-сосудистой системы и повысить выносливость.',
        sportType: 'Йога',
        status: 'completed',
        maxPlaces: 10,
        dateStart: new Date('2024-06-06T16:00:00'),
        durationMinutes: 60,
    },
    {
        trainerId: 2,
        title: 'Пилатес для укрепления мышц спины',
        description: 'Тренировка направлена на укрепление мышц спины и коррекцию осанки',
        sportType: 'Пилатес',
        status: 'pending',
        maxPlaces: 10,
        dateStart: new Date('2024-06-11T14:00:00'),
        durationMinutes: 60,
    },
    {
        trainerId: 2,
        title: 'Техника ударов в боксе',
        description: 'Обучение корректной технике ударов и блокировок в боксе',
        sportType: 'Бокс',
        status: 'pending',
        maxPlaces: 10,
        dateStart: new Date('2024-06-10T16:00:00'),
        durationMinutes: 60,
    },
    {
        trainerId: 2,
        title: 'Повышение гибкости через йогу',
        description: 'Урок для развития гибкости и укрепления тела через позы йоги',
        sportType: 'Йога',
        status: 'pending',
        maxPlaces: 10,
        dateStart: new Date('2024-06-07T09:00:00'),
        durationMinutes: 120,
    },
    {
        trainerId: 2,
        title: 'Утренняя зарядка',
        description: 'Зарядка для улучшения общего самочувствия',
        sportType: 'Фитнес',
        status: 'pending',
        maxPlaces: 10,
        dateStart: new Date('2024-05-11T16:00:00'),
        durationMinutes: 60,
    },
    {
        trainerId: 2,
        title: 'Урок йоги для начинающих',
        description: 'Занятие для освоения базовых асан и элементов йоги',
        sportType: 'Йога',
        status: 'pending',
        maxPlaces: 10,
        dateStart: new Date('2024-05-10T14:00:00'),
        durationMinutes: 60,
    },
];

export const mockOrders = [
    {
        clientId: 1,
        status: 'COMPLETED',
        workoutId: 1,
    },
    {
        clientId: 1,
        status: 'COMPLETED',
        workoutId: 4,
    },
    {
        clientId: 1,
        status: 'CANCELED_BY_ADMIN',
        workoutId: 2,
    },
    {
        clientId: 1,
        status: 'MISSING',
        workoutId: 3,
    },
    {
        clientId: 4,
        status: 'PENDING',
        workoutId: 6,
    },
    {
        clientId: 5,
        status: 'PENDING',
        workoutId: 6,
    },
    {
        clientId: 6,
        status: 'PENDING',
        workoutId: 6,
    },
    {
        clientId: 7,
        status: 'PENDING',
        workoutId: 6,
    },
    {
        clientId: 8,
        status: 'PENDING',
        workoutId: 6,
    },
    {
        clientId: 9,
        status: 'PENDING',
        workoutId: 6,
    },
    {
        clientId: 10,
        status: 'PENDING',
        workoutId: 6,
    },
    {
        clientId: 11,
        status: 'PENDING',
        workoutId: 6,
    },
    {
        clientId: 12,
        status: 'PENDING',
        workoutId: 6,
    },
    {
        clientId: 13,
        status: 'PENDING',
        workoutId: 6,
    },
    {
        clientId: 12,
        status: 'PENDING',
        workoutId: 5,
    },
    {
        clientId: 13,
        status: 'PENDING',
        workoutId: 5,
    },
];
